export const paths = {
  home: '/',
  loginUser: '/login-usuario',
  loginStaff: '/login-funcionario',
  register: '/registro',
  registerUser: '/registro-usuario',
  registerStaff: '/registro-funcionario',
  userMenu: '/menu-usuario',
  staffMenu: '/menu-funcionario',
  requests: '/mis-solicitudes',
  requestDetail: '/mis-solicitudes/:id',
  review: '/revision-solicitudes',
  notifications: '/notificaciones',
  upload: '/subir-archivos',
  chat: '/chat-audiencia',
};
