const errorStatus = {
  INVALID_CREDENTIALS: 401,
  INVALID_NAME: 400,
  INVALID_RUT: 400,
  PASSWORD_TOO_LONG: 400,
  MISSING_CREDENTIALS: 400,
  MISSING_REQUIRED_FIELDS: 400,
  INVALID_ROLE: 400,
  INVALID_TRAMITE_DECISION: 400,
  INVALID_TRAMITE_PAYLOAD: 400,
  INVALID_DOCUMENT: 400,
  DOCUMENT_TOO_LARGE: 413,
  TOO_MANY_DOCUMENTS: 400,
  INVALID_RESOLUTION_PAYLOAD: 400,
  UNSAFE_INPUT: 400,
  PAYLOAD_FIELD_TOO_LARGE: 413,
  CORS_ORIGIN_NOT_ALLOWED: 403,
  PASSWORD_TOO_SHORT: 400,
  TRAMITE_NOT_FOUND: 404,
  TRAMITE_TYPE_REQUIRED: 400,
  TRAMITE_UPDATE_REQUIRED: 400,
  RESOLUTION_FIELDS_REQUIRED: 400,
  USER_ALREADY_EXISTS: 409,
  NOTIFICATION_NOT_FOUND: 404,
};

export function errorHandler(error, req, res, next) {
  if (!error) return next();

  const status = errorStatus[error.message] || 500;
  const errorCode = status === 500 ? 'INTERNAL_SERVER_ERROR' : error.message;

  return res.status(status).json({
    error: errorCode,
  });
}
